# import sys
# print(sys.version)
# if 5 > 2:
#  print("Five greater than two")
# print("Five greater than two")
# x = 4
# print(x)
# x = "Wilson"
# print(x)

# x = str(3)
# y = int(3)
# z = float(3)
# print(x)
# print(y)
# print(z)
# x = 5
# y = "John"
# z= 3
# print(type(x))
# print(type(y))
# print(type(z))

# many values to multiple variabes

# x,y,z = "Orange", "Banana" , "Cherry"
# print(x)
# print(y)
# print(z)

# one value to multiple variable
# x=y=z= "Orange"
# print(x)
# print(y)
# print(z)

# unpack collection from list 

# fruits =["apple", "banana", "cherry"]
# x,y,z = fruits
# print(x)
# print(y)
# print(z)

# x=10
# y="Wilson"
# print(x,y)

# Gobal variable

x= "awesome"

def var_func():
    print("Python is "+x)

var_func()

